stages:
  - build
  - deploy
  - test

arm-build:
  stage: build
  only:
    - development
    - cicd
  script:
    - echo "dev build"
    - hostname ; pwd
    - ./compile fx1000
  artifacts:
    paths:
      - build/bin/tcogfs.x
    expire_in: 1 day
  tags:
    - h6ln19

arm-deploy:
  stage: deploy
  only:
    - development
    - cicd
  script:
    - echo "dev deploy"
  tags:
    - h6ln19

arm-test:
  stage: test
  only:
    - development
    - cicd
  script:
    - echo "dev testing"
    - cd job
    - JID=$(pjsub -z jid TCo383L72_IC_sample_fx1000 -x CMAKE_BUILD=1)
    - /usr/bin/pjwait ${JID}
  tags:
    - h6ln19

gpu-build:
  stage: build
  only:
    - master
  script:
    - echo "dev build"
    - hostname ; pwd
    - ./compile a100

gpu-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "dev deploy"

gpu-test:
  stage: test
  only:
    - master
  script:
    - echo "dev testing"
    - cd job
    - JID=$(pjsub -z jid TCo383L72_IC_sample_a100)
    - /usr/bin/pjwait ${JID}

stg-build:
  stage: build
  only:
    - master
  script:
    - echo "stg build"
    - hostname ; pwd
    - ./compile

stg-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "stg deploy"

stg-test:
  stage: test
  only:
    - master
  script:
    - echo "stg testing"
