stages:
  - build
  - deploy
  - test

arm-build:
  stage: build
  only:
    - development
    - cicd
  script:
    - echo "arm build"
    - hostname ; pwd
    - ./compile fx1000
  artifacts:
    paths:
      - build/bin/tcogfs.x
    expire_in: 1 day
  tags:
    - h6ln19

arm-deploy:
  stage: deploy
  only:
    - development
    - cicd
  script:
    - echo "arm deploy"
  tags:
    - h6ln19

arm-test:
  stage: test
  only:
    - development
    - cicd
  script:
    - echo "arm testing"
    - cd job
    - chmod 755 ./run_rt.sh
    - ./run_rt.sh
  tags:
    - h6ln19

gpu-build:
  stage: build
  only:
    - development
    - cicd
  script:
    - echo "gpu build"
    - hostname ; pwd
    - ./compile fx1000
  artifacts:
    paths:
      - build/bin/tcogfs.x
    expire_in: 1 day
  tags:
    - h6ln19

gpu-deploy:
  stage: deploy
  only:
    - development
    - cicd
  script:
    - echo "gpu deploy"
  tags:
    - h6ln19

gpu-test:
  stage: test
  only:
    - development
    - cicd
  script:
    - echo "gpu testing"
    - cd job
    - chmod 755 ./run_rt.sh a100
    - ./run_rt.sh
  tags:
    - h6ln19

stg-build:
  stage: build
  only:
    - master
  script:
    - echo "stg build"
    - hostname ; pwd
    - ./compile

stg-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "stg deploy"

stg-test:
  stage: test
  only:
    - master
  script:
    - echo "stg testing"
