stages:
  - build
  - deploy
  - test

arm-build:
  stage: build
  only:
    - development
    - cicd
  script:
    - echo "arm build"
    - hostname ; pwd
    - ./compile fx1000
  artifacts:
    paths:
      - build_fx1000/bin/tcogfs.x
    expire_in: 1 day

arm-deploy:
  stage: deploy
  only:
    - development
    - cicd
  script:
    - echo "arm deploy"

arm-test:
  stage: test
  only:
    - development
    - cicd
  script:
    - echo "arm testing"
    - cd job
    - chmod 755 ./run_rt.sh
    - ./run_rt.sh

gpu-build:
  stage: build
  only:
    - development
    - cicd
  script:
    - echo "gpu build"
    - hostname ; pwd
    - ./compile a100
  artifacts:
    paths:
      - build_a100/bin/tcogfs.x
    expire_in: 1 day

gpu-deploy:
  stage: deploy
  only:
    - development
    - cicd
  script:
    - echo "gpu deploy"

gpu-test:
  stage: test
  only:
    - development
    - cicd
  script:
    - echo "gpu testing"
    - cd job
    - chmod 755 ./run_rt.sh 
    - ./run_rt.sh a100

stg-build:
  stage: build
  only:
    - master
  script:
    - echo "stg build"
    - hostname ; pwd
    - ./compile

stg-deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "stg deploy"

stg-test:
  stage: test
  only:
    - master
  script:
    - echo "stg testing"

merge_request:
  only:
    - merge_requests
  script:
    - ./compile fx1000
    - ./compile a100
    - echo "gpu unit test"
    - ./job/unit_test.sh
