#!/bin/bash
set -e

MACHINE="fx1000"

. /usr/share/Modules/init/bash

# Loading fujitsu TCS library and cmake
module purge
module use /data/common/gfs/modulefiles/x86_64
module load tcsds/1.2.33
module load cmake/3.21.4
module unuse /data/common/gfs/modulefiles/x86_64

# Loading gfs modules
module use modulefiles
module load modulefile.tcogfs.${MACHINE}
module unuse modulefiles

# Compilation
cmake -Bbuild -S. \
	-DCMAKE_BUILD_TYPE=Release \
	-DUSE_RSM=OFF

\time --verbose cmake --build build -j $((`nproc`/2))

