#!/bin/bash

. /usr/share/Modules/init/bash

module use /nwpr/gfs/xb80/modulefiles/x86_64
module load cmake/3.19.3

module use /nwpr/gfs/xb80/modulefiles/fx100
module load fftw/3.3.7
module load netcdf/4.1.3
module load operlib
module load dms/v4

module use /nwpr/gfs/xb80/modulefiles/nceplibs/fx100
module load w3nco/v2.0.6

build_folder="build"
[[ -d ${build_folder} ]] && $SUDO rm -rf ${build_folder}
mkdir -p ${build_folder} && cd ${build_folder}

cmake -DCMAKE_BUILD_TYPE=Release -DUSE_RSM=OFF ../
make -j${NTHREADS:-16} VERBOSE=1

