#!/bin/bash

. /usr/share/Modules/init/bash

module purge
module use /data/common/gfs/modulefiles/x86_64
module load tcsds/1.2.33
module load cmake/3.21.4
module unuse /data/common/gfs/modulefiles/x86_64

# Loading gfs modules
module use /data/common/gfs/modulefiles/fx1000
module load netcdf/4.1.3
module load fftw/3.3.10.new_sp
module load dms/v4
module load operlib
module load w3lib/2.0.2
module unuse /data/common/gfs/modulefiles/fx1000

module list

build_folder="build"
[[ -d ${build_folder} ]] && $SUDO rm -rf ${build_folder}
mkdir -p ${build_folder} && cd ${build_folder}

cmake -DCMAKE_BUILD_TYPE=Release -DUSE_RSM=OFF  ../
make -j${NTHREADS:-50} VERBOSE=1 

