#!/bin/bash
#PJM -N "JTCo383L72"
#PJM -L "node=9"
#PJM -L rscgrp=small
#PJM -L elapse=03:30:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=384"
#PJM -g sum
#PJM -j
#PJM -S
#PJM -x PJM_CACHE_MODE=4

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

machine=fx1000
# TERR=GTOPO30
TERR=GMTED30
JCAP=383

#MPI=3840
MPI=384
OMP=1

if [ $JCAP = 639 ] ; then
  NPEX=8
  #NPEY=480
  NPEY=320
elif [ $JCAP = 383 ] ; then
  NPEX=4
  NPEY=96
fi
source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#source /users/xb80/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
