#!/bin/bash
#PJM -L rscunit=rscunit_ft01
#PJM -L rscgrp=fujitsu
#PJM -L "node=80:noncont"
#PJM -L elapse=2:00:00
####PJM --mpi "proc=3840"
#PJM --mpi proc=2560,max-proc-per-node=32
#PJM --mpi rank-map-bynode
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM -j
#PJM -S
#PJM -N "JTCo639L72"
#PJM -x PJM_CACHE_MODE=4

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

machine=fx1000
JCAP=383

#MPI=3840
MPI=2560
OMP=1

if [ $JCAP = 639 ] ; then
  NPEX=8
  #NPEY=480
  NPEY=320
elif [ $JCAP = 383 ] ; then
  NPEX=8
  NPEY=160
fi
source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#source /users/xb80/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
