#!/bin/ksh
#PJM -L "node=48:noncont"
#PJM -L rscgrp=research
#PJM -L elapse=2:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=768"
#PJM -j
#PJM -N JTCo383L72

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

machine=fx10
JCAP=383

MPI=768
OMP=1

if [ $JCAP = 639 ] ; then
  NPEX=2
  NPEY=384
elif [ $JCAP = 383 ] ; then
  NPEX=4
  NPEY=192
fi
source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
#. ${MDIR}/job/regression_stochy_physics.ksh
