#!/bin/ksh
#PJM -L "node=48:noncont"
#PJM -L rscgrp=research
#PJM -L elapse=2:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=768"
#PJM -j
#PJM -N JTCo639L72

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

MPI=768
OMP=1
NPEX=2
NPEY=384
machine=fx10

source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
