#!/bin/ksh
#PJM -L "node=48:noncont"
#PJM -L rscgrp=large-x
#PJM -L elapse=2:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=1536"
#PJM -j
#PJM -N JTCo639L72

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

machine=fx100
# TERR=GTOPO30
TERR=GMTED30
JCAP=639

MPI=1536
OMP=1

if [ $JCAP = 639 ] ; then
  NPEX=4
  NPEY=384
elif [ $JCAP = 383 ] ; then
  NPEX=8
  NPEY=192
fi
source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
#. ${MDIR}/job/regression_stochy_physics.ksh
