#!/bin/ksh
##PJM -L "node=48:noncont"
#PJM -L "node=48"
#PJM -L rscgrp=large-x
#PJM -L elapse=8:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=1536"
##PJM --mpi "rank-map-bynode"
##PJM --mpi "rank-map-hostfile=hostfile48_753"
#PJM -j
#PJM -N TCo639L72_fx100

set -x

MPI=1536
OMP=1
machine=fx100

source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

#-- enviornment
 user=`whoami`
 datamv='login11'
 dmsdb_home=/data/datacfs/${user}/data/dmsdb
 MDIR=/data1/datacfs/${user}/CWBGFS/TCo639L72_20180703
 DMSPATH=/package/${machine}/dms/dms.v4/bin
 GFSDIR=$MDIR
 GFSFIX=$MDIR/fix
 GFSWRK=${GFSDIR}/wrk_sample
 rm -rf $GFSWRK
 mkdir -p $GFSWRK

#-- dms data
 dtg='16070300'

 EXP='TCo639L72sample'
 indmsowner='b827'
 indmshead='TCo639L72_'
 indmstail='GJMGM'
 indmsdb='TCo639L72'

 outdmshead=${EXP}
 outdmstail=${indmstail}
 outdmsdb=${indmsdb}

#-- executable
 EXEC='MTCo639L72_'${machine}

#---------------------------------------------------------#
 indmsfile=${indmshead}${dtg}${indmstail}@${indmsdb}
 outdmsfile=${outdmshead}${dtg}${outdmstail}@${outdmsdb}

 if [ $indmsowner != $user ] ; then
  ${DMSPATH}/rdmsdbcrt -p ufs  $indmsdb
  ssh $datamv -n ${DMSPATH}/rdmscpy -l34 -k "*" ${indmsfile}@${indmsowner}@${datamv} ${indmsfile}
 fi

#-- write out running date tag
 echo $dtg > ${GFSWRK}/crdate

#-- write out file list
cat > ${GFSWRK}/filist << EOF
 &filst
 ifilin='ANADMS',
 ifilout='FCSTDMS',
 cwbout='${GFSWRK}/tmpdir/gfs_cwbout',
 bckfile='BCKOPS',
 phyout='${GFSWRK}/tmpdir/gfs_phyout',
 namlsts='${GFSWRK}/namlsts',
 crdate='${GFSWRK}/crdate',
 ocards='${GFSWRK}/ocards',
 cntrl='${GFSWRK}/gfsctl',
 &end
EOF


 export GFSDIR DMSPATH
 export NWPETC=${GFSDIR}/etc
 export NWPETCGLB=${GFSWRK}
 export GLB_TYPHINI="/nwp/npcagfs/TYP/M00/dtg/ty"
# export GLB_WTYPHINI="/data/datacfs/b827/data/obstyphoon"
 export FIXDIR=${GFSFIX}

 export ANADMS=${indmsfile}
 export FCSTDMS=${outdmsfile}
 export BCKOPS=BCK_TCo639_GJ30S@bckdms

${DMSPATH}/rdmspurge -f FCSTDMS
${DMSPATH}/rdmscrt -l34 FCSTDMS

 export FLIB_CNTL_BARRIER_ERR=FALSE



export O3FORC=${O3FORC:-${FIXDIR}/global_o3prdlos.f77}
export O3CLIM=${O3CLIM:-${FIXDIR}/global_o3clim.txt}
export AEROSOL_FILE=${AEROSOL_FILE:-${FIXDIR}/global_climaeropac_global.txt}
export EMMISSIVITY_FILE=${EMMISSIVITY_FILE:-${FIXDIR}/global_sfc_emissivity_idx.txt}


cd $GFSWRK
#====================================================================
ln -fs $O3FORC fort.28
ln -fs $O3CLIM fort.48
ln -fs $AEROSOL_FILE  aerosol.dat
ln -fs $EMMISSIVITY_FILE sfc_emissivity_idx.txt

ln -fs $FIXDIR/* .
cp $NWPETC/gfsctl $GFSWRK/gfsctl
cp $NWPETC/ocards $GFSWRK/ocards

#  cd $GFSWRK

# cd ${GFSDIR}

 FCT_MODEL=$MDIR/src/$EXEC
 /usr/bin/time -p mpiexec -n $MPI ${FCT_MODEL} 

 if [ $? != 0 ] ; then
  echo "error occured: fct model fail !!"
 fi

