#!/bin/ksh
#PJM -L "node=48:noncont"
#PJM -L rscgrp=large-x
#PJM -L elapse=2:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=1536"
#PJM -j
#PJM -N JTCo639L72

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

MPI=1536
OMP=1
NPEX=4
NPEY=384
machine=fx100

source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

. ${MDIR}/job/regression.ksh
