#!/bin/bash
#PJM -L "node=80:noncont"
#PJM -L rscgrp=fujitsu
#PJM -L elapse=2:00:00
#PJM -L node-mem=unlimited
#PJM --no-stging
#PJM --mpi "proc=1920"
#PJM -j
#PJM -N JTCo639L72
#PJM -x PJM_CACHE_MODE=4

set -x

MDIR=$(cd ..; pwd)
echo "MDIR=${MDIR}"

machine=fx10
# TERR=GTOPO30
TERR=GMTED30
JCAP=383

MPI=1920
OMP=2

if [ $JCAP = 639 ] ; then
  NPEX=8
  NPEY=$((${MPI}/${NPEX}))
elif [ $JCAP = 383 ] ; then
  NPEX=4
  NPEY=$((${MPI}/${NPEX}))
fi
#source /users/xa09/sample/setup_mpi+omp.${machine} $OMP

source /users/xb80/setup_mpi+omp.${machine} $OMP

#==============================================================================================================#

. ${MDIR}/job/regression.ksh
