# ##############################################################################
# Resolve dependency roots from GEPS_LIB module environment.
# ##############################################################################

macro(geps_resolve_root out_var)
  set(_geps_names ${ARGN})
  set(${out_var} "")
  foreach(_name IN LISTS _geps_names)
    if(DEFINED ENV{${_name}} AND NOT "$ENV{${_name}}" STREQUAL "")
      set(${out_var} "$ENV{${_name}}")
      break()
    endif()
    if(DEFINED ENV{${_name}_DIR} AND NOT "$ENV{${_name}_DIR}" STREQUAL "")
      set(${out_var} "$ENV{${_name}_DIR}")
      break()
    endif()
  endforeach()
endmacro()

geps_resolve_root(GEPS_NETCDF_ROOT NETCDF NETCDF_ROOT)
geps_resolve_root(GEPS_FFTW_ROOT FFTW FFTW_DIR FFTW3 FFTW_ROOT)
geps_resolve_root(GEPS_MCT_ROOT MCT MCT_DIR)
geps_resolve_root(GEPS_CPL_ROOT GEPS_COUPLER GEPS_COUPLER_DIR)
geps_resolve_root(GEPS_DMS_ROOT DMS DMS_DIR)
geps_resolve_root(GEPS_DMS38KEY_ROOT DMS38KEY DMS38KEY_DIR)
geps_resolve_root(GEPS_W3_ROOT W3LIB W3LIB_DIR)
geps_resolve_root(GEPS_OPERLIB_ROOT OPERLIB OPERLIB_DIR)
geps_resolve_root(GEPS_G2_ROOT G2LIB G2LIB_DIR)
geps_resolve_root(GEPS_PNG_ROOT LIBPNG LIBPNG_DIR)
geps_resolve_root(GEPS_JASPER_ROOT JASPER JASPER_DIR)
geps_resolve_root(GEPS_ZLIB_ROOT ZLIB ZLIB_DIR)
geps_resolve_root(GEPS_OPENBLAS_ROOT OPENBLAS OPENBLAS_ROOT OPENBLAS_DIR)

if(GEPS_FFTW_ROOT AND NOT DEFINED ENV{FFTW3})
  set(ENV{FFTW3} "${GEPS_FFTW_ROOT}")
endif()
if(GEPS_FFTW_ROOT AND NOT FFTW_ROOT)
  set(FFTW_ROOT "${GEPS_FFTW_ROOT}")
endif()
if(GEPS_NETCDF_ROOT AND NOT DEFINED ENV{NETCDF})
  set(ENV{NETCDF} "${GEPS_NETCDF_ROOT}")
endif()
if(GEPS_DMS_ROOT AND NOT DEFINED ENV{DMS})
  set(ENV{DMS} "${GEPS_DMS_ROOT}")
endif()

message(STATUS "GEPS_LIB paths:")
message(STATUS "  NETCDF   = ${GEPS_NETCDF_ROOT}")
message(STATUS "  FFTW     = ${GEPS_FFTW_ROOT}")
message(STATUS "  MCT      = ${GEPS_MCT_ROOT}")
message(STATUS "  CPL      = ${GEPS_CPL_ROOT}")
message(STATUS "  DMS      = ${GEPS_DMS_ROOT}")
message(STATUS "  DMS38KEY = ${GEPS_DMS38KEY_ROOT}")
message(STATUS "  OPENBLAS = ${GEPS_OPENBLAS_ROOT}")
if(DEFINED ENV{MKLROOT} AND NOT "$ENV{MKLROOT}" STREQUAL "")
  message(STATUS "  MKLROOT  = $ENV{MKLROOT}")
endif()
if(DEFINED ENV{NVHPC_ROOT} AND NOT "$ENV{NVHPC_ROOT}" STREQUAL "")
  message(STATUS "  NVHPC_ROOT = $ENV{NVHPC_ROOT}")
endif()
